# Generated by Django 4.2.3 on 2023-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
